modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="obsidian"
version="1.0.0"
displayName="Water and Lava"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Federico Cristina"
description='''
Water + Lava = Obsidian
'''

[[dependencies.obsidian]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"


[[dependencies.obsidian]]
    modId="mcreator_link"
    mandatory=false
    ordering="NONE"
    side="BOTH"

